/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clientes;

import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Oscar
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(this.MAXIMIZED_BOTH);
        URL url = getClass().getResource("/Clientes/images/Cliente1.png");
        ImageIcon img = new ImageIcon(url);
        setIconImage(img.getImage());
//        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/Clientes/images/Cliente1.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProperties1 = new org.jdesktop.swingx.LabelProperties();
        labelProperties2 = new org.jdesktop.swingx.LabelProperties();
        labelProperties3 = new org.jdesktop.swingx.LabelProperties();
        labelProperties4 = new org.jdesktop.swingx.LabelProperties();
        labelProperties5 = new org.jdesktop.swingx.LabelProperties();
        labelProperties6 = new org.jdesktop.swingx.LabelProperties();
        labelProperties7 = new org.jdesktop.swingx.LabelProperties();
        labelProperties8 = new org.jdesktop.swingx.LabelProperties();
        labelProperties9 = new org.jdesktop.swingx.LabelProperties();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        lblFondo = new org.jdesktop.swingx.LabelProperties();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelProperties1.setText("Nombre");
        getContentPane().add(labelProperties1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        labelProperties2.setText("Apellido Paterno");
        getContentPane().add(labelProperties2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        labelProperties3.setText("Apellido Materno");
        getContentPane().add(labelProperties3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        labelProperties4.setText("E-mail");
        getContentPane().add(labelProperties4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        labelProperties5.setText("Tel:");
        getContentPane().add(labelProperties5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        labelProperties6.setText("Direccion");
        getContentPane().add(labelProperties6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        labelProperties7.setText("Sexo");
        getContentPane().add(labelProperties7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        labelProperties8.setText("RFC");
        getContentPane().add(labelProperties8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        labelProperties9.setText("Empresa");
        getContentPane().add(labelProperties9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        jCheckBox1.setText("jCheckBox1");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, -1, -1));

        jCheckBox2.setText("jCheckBox2");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/fondoadminmenu1.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -60, 1610, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private org.jdesktop.swingx.LabelProperties labelProperties1;
    private org.jdesktop.swingx.LabelProperties labelProperties2;
    private org.jdesktop.swingx.LabelProperties labelProperties3;
    private org.jdesktop.swingx.LabelProperties labelProperties4;
    private org.jdesktop.swingx.LabelProperties labelProperties5;
    private org.jdesktop.swingx.LabelProperties labelProperties6;
    private org.jdesktop.swingx.LabelProperties labelProperties7;
    private org.jdesktop.swingx.LabelProperties labelProperties8;
    private org.jdesktop.swingx.LabelProperties labelProperties9;
    private org.jdesktop.swingx.LabelProperties lblFondo;
    // End of variables declaration//GEN-END:variables
}
