/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Micas;

import Home.Home;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import Business.Business;
import Data.Consultas;
import java.awt.Color;
import jc.Bolivia.ModernUI.Button.ButtonMUI;


/**
 *
 * @author LEO
 */
public class MenuMicas extends javax.swing.JFrame {

    private Dimension dim;
    //private Consultas  con;
   
///((public Color button_pressed = new Color(0,0,0);
////public Color texto_pressed = new Color(255, 255, 255);
    /**
     * Creates new form MenuMicas
     */
    public MenuMicas() {
        initComponents();
       // this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        // float escalar = 0.5F;
        int ancho = (int) (Toolkit.getDefaultToolkit().getScreenSize().width);
        int alto = (int) (Toolkit.getDefaultToolkit().getScreenSize().height);
       //    this.setSize(1280, 768);
        if (ancho <= 1280 && alto <= 780) {
            panelBotones.setPreferredSize(new Dimension(1165, 200));
            jsPanelTablaMicas.setPreferredSize(new Dimension(1165, 400));
            pnlTitulo.setPreferredSize(new Dimension(1280, 40));
        } else {
            panelBotones.setPreferredSize(new Dimension(1260, 200));
            jsPanelTablaMicas.setPreferredSize(new Dimension(1260, 400));
            pnlTitulo.setPreferredSize(new Dimension(1370, 40));
        }
          

         
        
        Business bs = new Business();
        bs.PoblarCombo("sexo", "sexo_desc", cboPrueba);
        bs.IniciarVentana(this, "Inventario");
       
     
        //bs.PoblarCombo("sexo", "sexo_desc", cboPrueba);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        AgregarMica = new javax.swing.JDialog();
        jsPanelTablaMicas = new javax.swing.JScrollPane();
        tablaMicas = new win8.swing.MetroTableUI();
        pnlTitulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnHome = new jc.Bolivia.ModernUI.Button.ButtonMUI();
        btnAgregar = new jc.Bolivia.ModernUI.Button.ButtonMUI();
        cboPrueba = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout AgregarMicaLayout = new javax.swing.GroupLayout(AgregarMica.getContentPane());
        AgregarMica.getContentPane().setLayout(AgregarMicaLayout);
        AgregarMicaLayout.setHorizontalGroup(
            AgregarMicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        AgregarMicaLayout.setVerticalGroup(
            AgregarMicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMicas.setPreferredSize(new java.awt.Dimension(1260, 360));
        jsPanelTablaMicas.setViewportView(tablaMicas);

        getContentPane().add(jsPanelTablaMicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        pnlTitulo.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Inventario de Micas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 608, 13, 608);
        pnlTitulo.add(jLabel2, gridBagConstraints);

        getContentPane().add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 40));

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));
        panelBotones.setFocusTraversalPolicyProvider(true);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Micas/images/Home.png"))); // NOI18N
        btnHome.setMnemonic('M');
        btnHome.setText("Menú");
        btnHome.setToolTipText("Ir a Menú");
        btnHome.setDefaultCapable(false);
        btnHome.setDoubleBuffered(true);
        btnHome.setFocusPainted(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHome.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Micas/images/HomeB.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        btnHome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnHomeKeyPressed(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Micas/images/add.png"))); // NOI18N
        btnAgregar.setMnemonic('A');
        btnAgregar.setText("Agregar");
        btnAgregar.setToolTipText("Ingresar Nuevo Registro de Mica");
        btnAgregar.setDoubleBuffered(true);
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregar.setIconTextGap(8);
        btnAgregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Micas/images/addB.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        btnAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAgregarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnAgregarKeyTyped(evt);
            }
        });

        cboPrueba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(cboPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(829, 829, 829))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(132, 132, 132))
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cboPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Micas/images/homeInventario.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
     //  this.requestFocus();
        Home hm = null;
        try {
            hm = new Home();
        } catch (Exception ex) {
            Logger.getLogger(MenuMicas.class.getName()).log(Level.SEVERE, null, ex);
        }
        hm.setVisible(true);
        this.dispose();
        this.setFocusable(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        new Business().IniciarDialogo(AgregarMica,700,400,"Agregar Micas");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnHomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHomeKeyPressed
        
    }//GEN-LAST:event_btnHomeKeyPressed

    private void btnAgregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAgregarKeyPressed
//       char car=(char) evt.getKeyCode();
//      if(car==evt.VK_A && evt.isAltDown()){
//   ButtonTeclado btn = new ButtonTeclado();
//   btn.keyPressed(evt);
//   System.out.println("hola");
   
    //o bien puedes colocar algún método que tengas.
//}

    }//GEN-LAST:event_btnAgregarKeyPressed

    private void btnAgregarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAgregarKeyTyped
        try {
            
            new Business().botonEnter(btnAgregar);
           //  this.setBackground(button_pressed);
      //  this.setForeground(texto_pressed);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAgregarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AgregarMica;
    private jc.Bolivia.ModernUI.Button.ButtonMUI btnAgregar;
    private jc.Bolivia.ModernUI.Button.ButtonMUI btnHome;
    private javax.swing.JComboBox<String> cboPrueba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jsPanelTablaMicas;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel pnlTitulo;
    private win8.swing.MetroTableUI tablaMicas;
    // End of variables declaration//GEN-END:variables
}
