/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

/**
 *
 * @author Oscar
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BarraHerramientas = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        txtMaterno = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        txtEmpresa = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        labelProperties1 = new org.jdesktop.swingx.LabelProperties();
        labelProperties2 = new org.jdesktop.swingx.LabelProperties();
        labelProperties3 = new org.jdesktop.swingx.LabelProperties();
        labelProperties4 = new org.jdesktop.swingx.LabelProperties();
        labelProperties5 = new org.jdesktop.swingx.LabelProperties();
        labelProperties6 = new org.jdesktop.swingx.LabelProperties();
        labelProperties7 = new org.jdesktop.swingx.LabelProperties();
        labelProperties8 = new org.jdesktop.swingx.LabelProperties();
        labelProperties11 = new org.jdesktop.swingx.LabelProperties();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/clientP.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 50, 50));

        BarraHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/fondoadminmenu1.png"))); // NOI18N
        getContentPane().add(BarraHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 70));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 140, 20));
        getContentPane().add(txtPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 140, 20));

        txtMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 140, 20));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 140, 20));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 140, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 140, -1));
        getContentPane().add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 140, -1));
        getContentPane().add(txtEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 140, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        labelProperties1.setText("Nombre");
        getContentPane().add(labelProperties1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        labelProperties2.setText("Primer Apellido");
        getContentPane().add(labelProperties2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        labelProperties3.setText("Segundo Apellido");
        getContentPane().add(labelProperties3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        labelProperties4.setText("E-mail");
        getContentPane().add(labelProperties4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        labelProperties5.setText("Tel:");
        getContentPane().add(labelProperties5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        labelProperties6.setText("Sexo");
        getContentPane().add(labelProperties6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        labelProperties7.setText("RFC");
        getContentPane().add(labelProperties7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        labelProperties8.setText("Empresa");
        getContentPane().add(labelProperties8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        labelProperties11.setText("Direccion");
        getContentPane().add(labelProperties11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jCheckBox1.setText("Descuento");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        jCheckBox2.setText("Credito");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 140, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/homeInterno.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaternoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        

       
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BarraHerramientas;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.LabelProperties labelProperties1;
    private org.jdesktop.swingx.LabelProperties labelProperties11;
    private org.jdesktop.swingx.LabelProperties labelProperties2;
    private org.jdesktop.swingx.LabelProperties labelProperties3;
    private org.jdesktop.swingx.LabelProperties labelProperties4;
    private org.jdesktop.swingx.LabelProperties labelProperties5;
    private org.jdesktop.swingx.LabelProperties labelProperties6;
    private org.jdesktop.swingx.LabelProperties labelProperties7;
    private org.jdesktop.swingx.LabelProperties labelProperties8;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
