package Login;

import Business.Business;
import Home.Home;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author LEO
 */
public class Login extends javax.swing.JFrame {

    Business bs;
    public static String userSession;
    Home hm;
    public Login() {
        initComponents();
//         try{ 
//    setIconImage(ImageIO.read(new File("img/logo.png")));
//  } 
//  catch (IOException e){
//    e.printStackTrace();
//  }
        URL url = getClass().getResource("/img/logo2.png");
        ImageIcon img = new ImageIcon(url);
        setIconImage(img.getImage());
        setLocationRelativeTo(null);
        setTitle("Ingresar al sistema");
        txtUsuario.requestFocus();
        AutoCompleteDecorator.decorate(cbxSesion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxSesion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 200, 40));

        txtContraseña.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyTyped(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 200, 40));

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Images/sigin.png"))); // NOI18N
        btnIngresar.setMnemonic('I');
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorderPainted(false);
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Images/cancel.png"))); // NOI18N
        btnCancelar.setMnemonic('C');
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Iniciar sesión como:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 110, 30));

        cbxSesion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terminal", "Empleado" }));
        getContentPane().add(cbxSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Images/imgLogin2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try {
            int cantidad;
            int valorCombo = cbxSesion.getSelectedIndex();
            if (valorCombo == 0) {
                bs = new Business();
                cantidad = bs.ComprobarTerminales("Login", "ComprobarTermUsuario", txtUsuario.getText());
                if (cantidad < 1) {
                    JOptionPane.showMessageDialog(this, "El nombre de usuario es incorrecto");
                    txtUsuario.requestFocus();
                    txtContraseña.setText("");
                } else {
                    bs = new Business();
                    cantidad = bs.ComprobarTerminales("Login", "ComprobarTermPass", new String(txtContraseña.getPassword()));
                    if (cantidad < 1) {
                        JOptionPane.showMessageDialog(this, "La contraseña es incorrecta");
                        txtContraseña.requestFocus();
                    } else {
                        bs = new Business();
                        cantidad = bs.ComprobarTerminales("Login", "ComprobarTermEstatus", txtUsuario.getText());
                        if (cantidad < 1) {
                            JOptionPane.showMessageDialog(this, "Esta terminal esta inactiva");
                            txtUsuario.setText("");
                            txtContraseña.setText("");
                            txtUsuario.requestFocus();
                        } else {
                            try {
                                Home hm = new Home();
                                hm.setVisible(true);
                                userSession=txtUsuario.getText().toUpperCase();
                                hm.lblUserSession.setText(userSession);
                                txtUsuario.setText("");
                                txtContraseña.setText("");
                                cbxSesion.setSelectedIndex(0);
                                this.dispose();
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(this, "Ocurrio un error al cargar el menú principal "+ e);
                            }

                        }
                    }
                }
            } else if (valorCombo == 1) {
                bs = new Business();
                cantidad = bs.ComprobarTerminales("Login", "ComprobarUsuario", txtUsuario.getText());
                if (cantidad < 1) {
                    JOptionPane.showMessageDialog(this, "El nombre de usuario es incorrecto");
                    txtUsuario.requestFocus(true);
                    txtContraseña.setText("");
                } else {
                    bs = new Business();
                    cantidad = bs.ComprobarTerminales("Login", "ComprobarPass", new String(txtContraseña.getPassword()));
                    if (cantidad < 1) {
                        JOptionPane.showMessageDialog(this, "La contraseña es incorrecta");
                        txtContraseña.requestFocus();
                    } else {
                        bs = new Business();
                        cantidad = bs.ComprobarTerminales("Login", "ComprobarUsuaEstatus", txtUsuario.getText());
                        if (cantidad < 1) {
                            JOptionPane.showMessageDialog(this, "Este usuario esta inactivo");
                            txtUsuario.setText("");
                            txtContraseña.setText("");
                            txtUsuario.requestFocus();
                        } else {
                             try {
                                Home hm = new Home();
                                hm.setVisible(true);
                                userSession=txtUsuario.getText().toUpperCase();
                                hm.lblUserSession.setText(userSession);
                                txtUsuario.setText("");
                                txtContraseña.setText("");
                                cbxSesion.setSelectedIndex(0);
                                this.dispose();
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(this, "Ocurrio un error al cargar el menú principal "+ e);
                            }

                        }
                    }
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int dato = JOptionPane.showConfirmDialog(null, "¿Estas seguro de cancelar y salir?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (dato == 0) {
            //se puede regresar aqui el codigo salir para quitar el ultimo
            System.exit(0);

        } else {
            cbxSesion.setSelectedIndex(0);
            txtUsuario.setText("");
            txtContraseña.setText("");

        }
        txtUsuario.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        char tecla = evt.getKeyChar();

        if (tecla == KeyEvent.VK_ENTER) {
            btnIngresar.doClick();
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyTyped
        char tecla = evt.getKeyChar();

        if (tecla == KeyEvent.VK_ENTER) {
            btnIngresar.doClick();
        }
    }//GEN-LAST:event_txtContraseñaKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        bs = new Business();
        bs.cerrar(txtUsuario);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cbxSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
